#!/bin/sh

#$ -S /bin/sh
#$ -cwd
#$ -V
#$ -q all.q
#$ -pe OpenMP 40

hostname

export g16root=/home/g03 
source $g16root/g16/bsd/g16.profile

export GAUSS_SCRDIR=/home/scr/$JOB_ID
mkdir /home/scr/$JOB_ID

./exe_6inter.txt  

rm -rf /home/scr/$JOB_ID


#sleep 500
